# This is the config file for the Bot Killer extension.

template: bot.twig
# Set Max seen bot in honeypot network 0-255
# Only bot last seen under 50 days will be blocked
max_last_seen: 50
# Only search engine bot allowed
# Please read http://www.projecthoneypot.org/httpbl_api.php for more information
min_visitor_allowed: 0
# Minimal threat score 0-255
# Please read http://www.projecthoneypot.org/httpbl_api.php for more infomation
min_threat_score: 30
# Honeypot private key
private_key: your-key-here
# All naughty bot will redirected here
bot_page: go-away
db_log: true
txt_log: true
